<?php

  // You can change these values to modify the question generator

  const BST_HEIGHT_LIMIT = 5;
  
  const BST_RANGE_LOWER_BOUND = 1;
  const BST_RANGE_UPPER_BOUND = 99;

  const BST_SIZE_LOWER_BOUND = 3;
  const BST_SIZE_LINKED_LIST_UPPER_BOUND = 5;
  const BST_SIZE_UPPER_BOUND = 10;

  const HEAP_RANGE_UPPER_BOUND = 99;
  const HEAP_RANGE_LOWER_BOUND = 1;

  const HEAP_SIZE_UPPER_BOUND = 10;
  const HEAP_SIZE_LOWER_BOUND = 3;

  const GRAPH_TEMPLATE_EDGE_DIRECTION_CHANGE_DEFAULT_CHANCE = 50;
  const GRAPH_TEMPLATE_EDGE_BIDIRECTION_CHANGE_DEFAULT_CHANCE = 10;
?>